### ISSUE TITLE
How to use this in ionic app.

### ISSUE THREAD

**Issue by haris1775** [chemerisuk/cordova-plugin-firebase-inappmessaging#5]

**Comment by guibarbosadev** [comment]
This plugin simply adds  Firebase In-app Messagin Android/IOS "native plugins". All you have to do is to install this cordova plugin on your project, since the "native plugins" will handle everything.
If you learn more about Firebase In-app Messaging. Checkout: https://firebase.google.com/products/in-app-messaging

Installation: 
`ionic cordova plugin add cordova-plugin-firebase-inappmessaging`
